import './images/skynet-music.png';
import './images/skynet_music_logo_sm.png';
import './images/skynet_music512.png';
import './images/skynet_music192.png';
import './images/maskable_icon.png';
import './stlye/main.css';
import '../manifest.json';
// import './stlye/font-awesome-4.7.0/css/font-awesome.min.css';
// import './stlye/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2';
// import './stlye/font-awesome-4.7.0/fonts/fontawesome-webfont.woff';
// import './stlye/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf';
// import './stlye/font-awesome-4.7.0/fonts/fontawesome-webfont.svg';
// import './stlye/font-awesome-4.7.0/fonts/fontawesome-webfont.eot';